### ISSUE TITLE
Registering a wizard in TCA

### ISSUE THREAD

**Issue by prentice87** [rupertgermann/tt_news#1]
Hi i'm trying to use this tt_news with Typo3 CMS 7.4.0 and i'm getting the Message:

The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/sctipt.php in your TCA. 

When trying to add the Plugin to a page. Any solution?

**Comment by rupertgermann** [comment]
fixed in version 7.6.0
