### ISSUE TITLE
Call to a member function setTSlogMessage() on null [8.7.12]

### ISSUE THREAD

**Issue by xerc** [rupertgermann/tt_news#103]
https://github.com/rupertgermann/tt_news/blob/a9322308bef644b614fa9831c1c743d8d1f0466a/pi/class.tx_ttnews.php#L3897

**Comment by OliverTempel** [comment]
tt_news/pi/class.tx_ttnews.php
Line 31 + use TYPO3\CMS\Core\TimeTracker\TimeTracker;
Line 175 +if(!is_object($GLOBALS['TT'])){$GLOBALS['TT'] = new TimeTracker();}

Quick & Dirty Workaround
Tested in TYPO3 8.7.15 with Version 8.7.0

**Comment by rupertgermann** [comment]
fixed in 388d8cd
