### ISSUE TITLE
Error Class 'GeneralUtility' not found when used with Typo3 8.7.15

### ISSUE THREAD

**Issue by baden32** [rupertgermann/tt_news#107]
I just installed the latest zip of tt_news (version 8.7 & Typo3 8.7.15) and unfortunately I get an error when trying to click on "News Admin" Typo3 menu (left column):

Oops, an error occurred!
Class 'GeneralUtility' not found

A NEWS sysfolder has been created and I can add/define news category/news record in List mode.

Is that a know problem? A workaround already exists?
Thanks in advance for your help.
Joel

**Comment by rupertgermann** [comment]
please use latest master where this issue should be fixed
