### ISSUE TITLE
Error when running "Row updater" upgrade wizard

### ISSUE THREAD

**Issue by lgescobar** [rupertgermann/tt_news#109]
Hello there,

I found a problem when running the "Row updater" if this extension (branch `feature/87refactoring`) is installed along with `templavoilaplus/templavoilaplus`. The tables `be_groups` and `be_users` end having unwanted TCA entries because of the global variable `$tempColumns` not being cleared on these files:

- `EXT:tt_news/Configuration/TCA/Overrides/be_groups.php`
- `EXT:tt_news/Configuration/TCA/Overrides/be_users.php`

Kind regards,
Luis Garcia

**Comment by rupertgermann** [comment]
please use latest master where this issue should be fixed
