### ISSUE TITLE
[BUG] generic marker must be a string

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#111]
Generic markers can not be integers any more with latest master.

Uncaught TYPO3 Exception:
`PHP Warning: strtoupper() expects parameter 1 to be string, array given in ...\web\typo3conf\ext\tt_news\Classes\Plugin\TtNews.php line 2245`

TYPO3 8.7.20
tt_news 9.5.0

**Comment by rupertgermann** [comment]
good catch ;-)
fixed in 8e6724c7c8a62a38b0194c0ae9fd0607de14a570 (master)
