### ISSUE TITLE
Pagebrowser and noNewsToListMsg not working in 9.5.0

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#113]
The list view pagebrowser (pi_list_browseresults) is gone / not shown with the latest master v9.5.0. 
Also the configured noNewsToListMsg is not shown anymore. 

Tested with:
tt_news 9.5.0 (8e6724c7c8a62a38b0194c0ae9fd0607de14a570)
TYPO3 8.7.20
PHP 7.2

**Comment by rupertgermann** [comment]
thanx for testing :-)
will have a look

**Comment by rupertgermann** [comment]
both fixed. see (fae15e7)

**Comment by Patta** [comment]
great thanks!
