### ISSUE TITLE
[BUG] Access level to RG\TtNews\Module\NewsRecordlist::makeQueryArray() must be public

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#114]
Bug after latest clean up commit 36fa473361b2b3ad6164db57bc039596839d4c17

`Fatal error: Access level to RG\TtNews\Module\NewsRecordlist::makeQueryArray() must be public (as in class TYPO3\CMS\Recordlist\RecordList\AbstractDatabaseRecordList) in REMOVED\web\typo3conf\ext\tt_news\Classes\Module\NewsRecordlist.php on line 52`

TYPO3 8.7.20
tt_news 9.5.0 36fa473361b2b3ad6164db57bc039596839d4c17
PHP 7.2

**Comment by rupertgermann** [comment]
fixed in 6ba344c
thanks for testing
