### ISSUE TITLE
Pagination Icons in BE-Modul broken on 8.7

### ISSUE THREAD

**Issue by frankschuessler** [rupertgermann/tt_news#115]
Next and previous icons in News Record List Module in TYPO3 8.7.22 are broken.
 
It seems that pathes to control_*.gif Icons are rendered incorrect in `NewsRecordlist->renderListNavigation()` in `tt_news/Classes/Module/NewsRecordlist.php` line 264ff.

The `IconFactory::skinImg` should be called with Icon Filename (e.g. `control_first.gif`) as `src` instead of fullpath in `wHattribs` parameter.

**Comment by rupertgermann** [comment]
fixed
