### ISSUE TITLE
SQL Error while inserting News without endtime

### ISSUE THREAD

**Issue by xQuai** [rupertgermann/tt_news#116]
Hello,

i'm on TYPO3 Version 8 with MySQL 5.7.24.

If i want to save a news without a specific endtime, i get the following error message.
`SQL error: 'Incorrect integer value: '' for column 'endtime' at row 1' `

Can somebody help me?

**Comment by rupertgermann** [comment]
could it be that you have mysql running in "strict mode" ?
but then you should have such Problems in many other places in the TYPO3  Backend, too.

**Comment by xQuai** [comment]
Yeah, MySQL is running in strict mode ("STRICT_TRANS_TABLES"). Should i deactivate it? This is the only place where i got an SQL Error.

**Comment by rupertgermann** [comment]
yes, disable it.
and feel free to open a ticket here "make tt_news run in mysql strict mode"
thanks
Rupert

**Comment by xQuai** [comment]
Okay. I will do it.

My SQL-Modes are now 
`"ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`
before they were `"STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`.

Are they alright?

**Comment by rupertgermann** [comment]
looks OK. In my my.cnf I have simply:
sql_mode = NO_ENGINE_SUBSTITUTION
