### ISSUE TITLE
make tt_news run in mysql strict mode

### ISSUE THREAD

**Issue by xQuai** [rupertgermann/tt_news#117]
In MySQL 5.7 and higher strict mode is enabled by default and is causing some errors ([see](https://github.com/rupertgermann/tt_news/issues/116))
Can we make tt_news work correct in Mysql Strict mode?

Thanks.

**Comment by rupertgermann** [comment]
fixed. Now all date/datetime fields in tt_news and tt_news_cat are configured like e.g. the datetime fields in tt_content. 
I don't see problems with mysql strict mode anymore - do you ?

**Comment by xQuai** [comment]
It looks fine.
Nice Work.
