### ISSUE TITLE
2: SQL error: 'Incorrect integer value: '' for column 'shortcut' at row 1' (tt_news_cat:NEW...)

### ISSUE THREAD

**Issue by netzcoop** [rupertgermann/tt_news#119]
hello 

i have problems to save new categories with the columns shortcut and single_pid.

my BUGFIX:
To resolve this problem it is necessary in
EXT:tt_news/Configuration/TCA/tt_news_cat.php
to extend the configs for the both columns shortcut and single_pid
with 'default' => 0,
in example

`
return [

	'columns' => [

		'shortcut' => [

			// ....

			'config' => [

				// ....

				'default' => 0,

			]

		],

	]

]
`

**Comment by rupertgermann** [comment]
Hi, 
thanks for the patch but there was still one default value missing for the field "parent_category". I added it and committed it to master. see a50ebb64ff0d085e201950d3bc69d520ee5db419

greetings 
Rupert
