### ISSUE TITLE
ArgumentCountError in backend module

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#121]
```
ArgumentCountError
Too few arguments to function RG\TtNews\Module\NewsAdminModule::mainAction(), 1 passed and exactly 2 expected

in ...\web\typo3conf\ext\tt_news\Classes\Module\NewsAdminModule.php line 253
```

PHP 7.3
TYPO3 9.5.5
Composer mode

**Comment by rupertgermann** [comment]
can you still reproduce this ? 
works for me in tt_news master and TYPO3 8.7 and 9.5

**Comment by Patta** [comment]
Yes, the issue is still there with tt_news master and TYPO3 9.5.7.
If you use typo3-secure-web, the module icon is also missing.
In my case the backend module does not work at all with the modern backend and manage tt_news items with the list module is a lot easier.

**Comment by Patta** [comment]
I have found the problem, the system feature in 9.5 "simplifiedControllerActionDispatching" must be deactivated.

Basicly exactly the same issue as described here: https://github.com/xperseguers/t3ext-image_autoresize/issues/21
Solution here: https://github.com/xperseguers/t3ext-image_autoresize/commit/8de509ed85b8a174f645e971875cc457a7dde1f0
