### ISSUE TITLE
TCA bug - causes exception in upgrade wizard

### ISSUE THREAD

**Issue by w010** [rupertgermann/tt_news#124]
https://github.com/rupertgermann/tt_news/blob/4b9da3d535ce1ed9e320ec2c56345ec75688d672/Configuration/TCA/Overrides/be_groups.php#L4

In feature/87refactoring there have to be:
unset($tempColumns)
before
$tempColumns['tt_news_categorymounts']
And the same for TCA/Overrides/be_users.php

It's already fixed in feature/9dev branch. Please fix this here too.
It causes adding other table's fields to be_groups TCA, which causes exceptions in install tool upgrade wizard / migrating l10n fields.

**Comment by rupertgermann** [comment]
it's fixed in branch master which works for TYPO3 8.7 and 9.5 and which is also published on TER
