### ISSUE TITLE
Links in News RTE not working

### ISSUE THREAD

**Issue by sitecoreModules** [rupertgermann/tt_news#125]
When I set an internal Link in an News RTE it doe not get resolved. 
Links look like this:  t3://page?uid=277

**Comment by rupertgermann** [comment]
can't reproduce. When I set an internal link in my test instance it works. Can you give us some more details? which tt_news version, which  TYPO3 version, etc.  ?

greetings 
rupert

**Comment by sitecoreModules** [comment]
![link2](https://user-images.githubusercontent.com/5112607/59179175-81f64600-8b61-11e9-8e23-4a5a5febc7c7.png)
thanks rupert.  Here more details:

tt_news                    9.5.2
TYPO3 Version	9.5.7
Webserver	        LiteSpeed
PHP Version	        7.2.18
Database (Default)	MySQL 5.7.26
Application Contex  Production
Operating System	Linux 3.10.0-962.3.2.lve1.5.25.8.el7.x86_64
Bootstrap Package	10.0.6

**Comment by rupertgermann** [comment]
I just tried to reproduce this with the current Version and it works as it should. The Sourcecode view in RTE shows: <a href="t3://page?uid=53">link</a> and in the Frontend the link points to the correct page. 
Maybe this is a misunderstanding: the RTE never resolves this links - this is done by the Frontend Rendering.

**Comment by svenbehl** [comment]
Hi rupert,

same think here. The links (site, file) are not translated and shown as t3://..... in the website.

TYPO3: 9.5.19
tt_news: 9.5.3
Bootstrap Package: 10.0.9

regards sven

**Comment by msollmann** [comment]
Can confirm this.

TYPO3: 9.5.23
tt_news: 9.5.3 with default template
No Bootstrap Package

**Comment by DavidBruchmann** [comment]
are links in common content-elements working?
You've to save a record to test it, this test works even without making changes, just you have to make a backup of the record first perhaps.

**Comment by msollmann** [comment]
I just found out, it was the order of the static templates...

**Comment by sitecoreModules** [comment]
so cool thanks @msollmann works now for me. I set the tt news templates on top!
