### ISSUE TITLE
Related News unaccessible in Typo3 9.5.8

### ISSUE THREAD

**Issue by FranzBl** [rupertgermann/tt_news#126]
When I use tt_news in 9,5,8, selecting a "related news" to a given news record, it leads to a message "no news_id given". The error occurs only when speaking URLs are used. This error was known in earlier Typo3 versions too and was related to realurl extension.
In Typo3 9, speaking URLs are no longer handled via realurl but by the new Sites management. I didn't find any information how to bypass the "no news_id given" error.
Is this a tt_new bug in this new version, or is it a configuration error?
Please help.

**Comment by rupertgermann** [comment]
Hi Franz,
that was indeed a bug and no misconfiguration.

fixed with https://github.com/rupertgermann/tt_news/commit/de92ecab2e803f2545bf0d26bd79139b2b8e3236

greetings
Rupert

**Comment by FranzBl** [comment]
I suppose that will be fixed in the next release? I'm an old software veteran, so I think about if to edit the original code in place, or will it be some day overwritten by an update?

**Comment by rupertgermann** [comment]
just uploaded tt_news 9.5.3 to TER where this bug is fixed.
