### ISSUE TITLE
No output in Frontend 7.6.1, PHP 5.5, TYPO3 7.6.10

### ISSUE THREAD

**Issue by vandres** [rupertgermann/tt_news#13]
Hi, today I updated from 3.6.0 to 7.6.1 together with a TYPO3-Update to 7.6. Unfortunatly there is not any output anymore in the frontend. The Backend TCA, plugin-placement etc. seem to work. Am I missing something? The TYPO3 is running in Composer Mode

**Comment by vandres** [comment]
I fixed it with adding this to my composer.json

```
    "autoload": {
        "classmap": [
            "www/typo3conf/ext/tt_news/lib/",
            "www/typo3conf/ext/tt_news/pi/",
            "www/typo3conf/ext/tt_news/mod1/"
        ]
    }
```

**Comment by derhecht** [comment]
I think you have a wrong setup. Using TYPO3 7.6.x with just a single "typo3-ter/tt-news": "^7.6" in the main composer file and it works. Try re-adding it by composer require not by just adding the line to the composer.json by yourself.
Do you use the composer/TYPO3 way which is described on https://composer.typo3.org/ especially  the composer.json setup? Try to run composer require typo3/cms right after adding repositories.
