### ISSUE TITLE
pagination not working php 7.2 ,TYPO3 8.7, tt_news v9.5.3

### ISSUE THREAD

**Issue by bharatdrc** [rupertgermann/tt_news#136]
pagination is not working **php 7.2** ,**TYPO3 8.7**, **tt_news v9.5.3**.
i tried with disabling realurl so it is not issue of realurl.
pointer parameter is passed correctly but pagination is somehow not working.

**Comment by rupertgermann** [comment]
Hi,
in my local test instance with the same versions this works as expected. The link looks like: ...index.php?id=1234&tx_ttnews%5Bpointer%5D=2&cHash=a557db97263b2c87f8b0b67885271eec

greetings 
Rupert

**Comment by bharatdrc** [comment]
solved with 
plugin.tt_news.latestWithPagebrowser = 1
is it added for any reason as we can disable pagination from plugin settings.
but thanks for reply.
