### ISSUE TITLE
mySQL strict mode problem

### ISSUE THREAD

**Issue by chesio** [rupertgermann/tt_news#137]
When I try to localize existing tt_news record, I get following error (in MySQL strict mode):

> 2: SQL error: 'Incorrect integer value: '' for column 'page' at row 1' (tt_news:NEW5de9268c1c333915866059)

Fix is simple, provide default value for `page` column in TCA (see #117) - patch incoming.

**Comment by Patta** [comment]
l18n_parent column is also affected and needs the default value

**Comment by chesio** [comment]
@Patta Thanks for noticing, I've updated the PR.

**Comment by Patta** [comment]
resolved with v10.0.0
