### ISSUE TITLE
Plugin's method displayList must be public again

### ISSUE THREAD

**Issue by w010** [rupertgermann/tt_news#140]
\RG\TtNews\Plugin\TtNews::displayList() - that method's scope was changed lately (between 9.5.0 and 9.5.3 from undefined to protected. It must be public, without being able to call it from hook object we are unable to define any custom codes, that uses customized list behaviour.
Also the same with displaySingle and all other displayXX methods. They all must be kept public to be able most of custom ttnews codes (theCode) still work.
Example:

```
-- ext_localconf.php:
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['tt_news']['extraCodesHook'][] = \My\Ext\TtNews\Hook\NewLists::class;

-- hook class for custom code - NewLists.php:
namespace \My\Ext\TtNews\Hook;
class NewLists {
    extraCodesProcessor(\RG\TtNews\Plugin\TtNews &$parentObj) {
        switch($parentObj->config['code']) {
         case 'NEWS_MY_CUSTOM_LIST':
            // do something before, manipulate config or whatever
            ...
            // NOW CAUSES FATAL ERROR, MUST BE ABLE TO CALL IT FROM OUTSIDE
            return $parentObj->displayList();
}
````

**Comment by bernhardberger** [comment]
+1
