### ISSUE TITLE
Typo3 9: News Admin Backend Module missing

### ISSUE THREAD

**Issue by rk-mxp** [rupertgermann/tt_news#141]
I installed tt_news on a Typo3 9.5 system and the News Admin Module is missing in the Backend.
This is also true for Typo3 8 and Typo3 7. 

Background: I'm in the process of upgrading a site from Typo3 6 to Typo3 9. This happens with an admin user. In Typo3 6 the module appears.

Are additional steps required for the module to appear beside activating the extension?

**Comment by rupertgermann** [comment]
the tt_news admin module has to be enabled in the settings module.
Configure extensions -> tt_news

hth 
rupert

**Comment by rk-mxp** [comment]
Ah I see, thanks!
The extension configuration is now somewhere else entirely in Typo3 9...

Problem solved, you can close the issue.
