### ISSUE TITLE
External renderer: PHP warning in single view

### ISSUE THREAD

**Issue by Hawkeye1909** [rupertgermann/tt_news#142]
I tried my luck porting the old template into one using fluid. I got list view working but in single view I get a PHP warning (with debug presets):
`PHP Warning: array_flip() expects parameter 1 to be array, null given in .../httpdocs/typo3conf/ext/tt_news/Classes/Plugin/TtNews.php line 1855`

The problem is that you want to use array_flip() with the renderMarkers but these were not filled before when $useUpstreamRenderer is true.

**Comment by rupertgermann** [comment]
fixed with #174
