### ISSUE TITLE
remove final stdwrap

### ISSUE THREAD

**Issue by OlivierSC** [rupertgermann/tt_news#146]
https://github.com/rupertgermann/tt_news/blob/48ed4ba59c5795bcfe4538d3e999f82705fdc05e/Classes/Plugin/TtNews.php#L466

Since TYPO3 V6, stdWrap is automatically applied to "USER/USER_INT" object by TYPO3, without any additional php code. 
With the additional stdWrap at then end of main_news() function, the stdWrap is applied twice.

Solution : return normal $content.
`return $content;`

**Comment by Patta** [comment]
fixed with v10.0.0
