### ISSUE TITLE
Typo3 tt_news disabled date

### ISSUE THREAD

**Issue by ArunPatal** [rupertgermann/tt_news#147]
I am facing problem with tt_news in typo3 version 6.2.11. I can not set date above 2020 year. I can set till 31.12.2020 and after that all dates are disabled. I have taken 2 screenshot of it. Any hint or solution would help me
[Please check image ](https://i.stack.imgur.com/7OpdU.png)
Thanks

**Comment by rupertgermann** [comment]
hi,
the 2020 is hardcoded in the field config of the endtime field in older tt_news versions.
https://github.com/rupertgermann/tt_news/blob/feature/tt-news-76/Configuration/TCA/tt_news.php
You'll need to edit that file and put in something like 2038

greetings
Rupert

**Comment by ArunPatal** [comment]
Hello, Thank you for the solution. Right now i do not have server ftp access. Is it possible to do this via constants or setup configuration?

**Comment by rupertgermann** [comment]
this setting is in TCA in the config section which can partly be overridden by pageTsConfig, but unfortunately not the "range" property.
https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceForm.html#config
sorry you have to change the code of the file on the server, maybe with an extension like this https://extensions.typo3.org/extension/kmcs_fileedit/

**Comment by ArunPatal** [comment]
thank you :) appreciate your help

**Comment by ArunPatal** [comment]
Hello Rupert,

I am having same problem in other site and this time changing endtime range did not work.
I am adding tca.php file which is located in tt_news.  I changed it to **'upper' => mktime(0,0,0,12,31,2030)**

[tca.txt](https://github.com/rupertgermann/tt_news/files/4764795/tca.txt)
![cal](https://user-images.githubusercontent.com/30784805/84388093-4cf95500-abf4-11ea-9920-c360162c1463.png)

Any idea ???

**Comment by rupertgermann** [comment]
hi, 
the line "mktime(0,0,0,12,31,2030)" seems to be correct. maybe it's overwritten somewhere else. You can use the Configuration backend module ($GLOBALS['TCA']) to find out which value TYPO3 actually sees.

**Comment by ArunPatal** [comment]
I checked $GLOBALS['TCA'] and value there seems to be fine. But still dates after 2020 are disabled.
![tca-config](https://user-images.githubusercontent.com/30784805/84442457-f57fd700-ac3d-11ea-9d9d-ebf0b82cb066.png)

**Comment by ArunPatal** [comment]
Hi,
Thank you for nice tip ($GLOBALS['TCA']) & your help..
I Checked configuration and value was fine there..
It was another extension which use tt_news :)
