### ISSUE TITLE
pid_list not working propper / initPidList 

### ISSUE THREAD

**Issue by maikcaro** [rupertgermann/tt_news#151]
As soon I set the pid_list option or select "Page(s) with tt_news records" in the plugin tt_news returns a alert.
It looks like initPidList  fails.

**Comment by rupertgermann** [comment]
hi, 
in which tt_news and TYPO3 version did you get this error?
at least in the current version 10 this seems to be fixed

**Comment by maikcaro** [comment]
Hi Rupert,
sorry, but I don't remember the problem.
I think I used a workaround.
