### ISSUE TITLE
TYPO3 v10 LTS compatibility

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#154]
Please make this classic and still relevant extension compatible with TYPO3 v10 LTS.

This issue can be used as a collection for open tasks, bugs or tests of the current [v10 branch](https://github.com/rupertgermann/tt_news/tree/feature/tt_news-v10).

**Comment by msollmann** [comment]
Would be great!

**Comment by Patta** [comment]
#10.0.0

**Comment by Patta** [comment]
v10.0.0

**Comment by Patta** [comment]
resolved with v10.0.0
