### ISSUE TITLE
Exception is thrown when trying to edit records in BE folder

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#159]
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1534710048: No pseudo-site found in root line of page XYZ`

Same issue as in a older tt_address version: https://wiki.typo3.org/Exception/CMS/1534710048

**Comment by rupertgermann** [comment]
hi, how exactly can I reproduce this error?
seems not to happen in my v9 and v10 test instances

**Comment by Patta** [comment]
In my instance (9.5 LTS), i have a folder in a site with tt_news records. After upgrade to tt_news 10 and running all upgrade wizards, the exception is thrown on edit of a record in this folder. https://github.com/FriendsOfTYPO3/tt_address/issues/293
