### ISSUE TITLE
Upgrade wizard to migrate imagecaption and imagetitletext to FAL image

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#161]
Is it possible to add a upgrade wizard to tt_news v10 to migrate the values from field `imagecaption` and `imagetitletext` to the FAL image field `description` and `title` ?

**Comment by rupertgermann** [comment]
now the update wizard for tt_news images handles also alt/title and caption texts
Todo: make the FE plugin aware of these fields

**Comment by rupertgermann** [comment]
done. please test

**Comment by Patta** [comment]
Big up! Works great. Happy holiday!
