### ISSUE TITLE
Upgrade wizard and FAL for category images missing

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#162]
Please add or extend the ugrade wizard for moving tt_news_cat images from "uploads/pics" to "fileadmin/migratedNewsAssets/Images" and register them in FAL. 
Without that, tt_news still requires the legacy uploads/pics directory.

Additionaly new "FAL" category images are not rendered with marker ###NEWS_CATEGORY_IMAGE###.

Thanks.

**Comment by rupertgermann** [comment]
here's the updater
https://github.com/rupertgermann/tt_news/commit/e45dcce45e7a80df293b1c0d10f0d9257e9ef6de
I'll now have a look at rendering of these images in FE

**Comment by rupertgermann** [comment]
Fixed it

**Comment by Patta** [comment]
Big up! Works great. Happy holiday!
