### ISSUE TITLE
In BE: Related files are missing after update to 10.0.0

### ISSUE THREAD

**Issue by doni32** [rupertgermann/tt_news#165]
When I update tt_news to 10.0.0 in Typo3 9.5.24, I no longer see the related files in the BE.
They are still visible in the FE, but only as long as I do not save this news in the BE.
I could reassign the files, but I have assigned around 1000 news items with different numbers of related files.
Can I somehow automatically reassign them?

german:
Wenn ich in Typo3 9.5.24 tt_news auf 10.0.0 aktualisiere, sehe ich im BE die Related files nicht mehr.
Im FE sind sie noch sichtbar, aber nur solange ich diese News im BE nicht speichere.
Ich könnte die Dateien neu zuordnen, aber ich habe ca. 1000 News mit unterschiedlich vielen Related Files zugeordnet.
Kann ich die irgendwie automatisiert wieder zuordnen?

**Comment by rupertgermann** [comment]
have you tried the upgrade wizard "migrateFileAttachmentsToFal" ?

**Comment by doni32** [comment]
Thanks! Did the upgrades in this order:
[tt_news files to FAL] Migrates tt_news files from "uploads/media" to FAL
[tt_news images to FAL] Migrates tt_news images from "uploads/pics" to FAL
Introduce URL parts ("slugs") to all tt_news entries of EXT:tt_news
