### ISSUE TITLE
Switch to fluid template rendering

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#174]
To be more flexible in the development and design of frontend templates and to support the nowadays standard typo3 template engine, it would be great if tt_news would support fluid templates or would be switched from marker based templates to fluid templates.

Currently, template areas can be swapped to fluidtemplate via genericmarkers, but this is not a nice approach.

THX!

**Comment by rupertgermann** [comment]
hi, 
thanks for the reminder. 
Actually I have something like this in my "archives" from a project I made in 2014 or so :-)
it's a simple "use fluid or classic templating" switch which ensures downwards compatibility in case of "classic templating" and in case of "fluid" collects the all the needed data and hands it over to fluid.

**Comment by rupertgermann** [comment]
just pushed a new version of tt_news to master where you can enable Fluid rendering. A bunch of example fluid templates is included, too.
set `plugin.tt_news.useFluidRendering=1` in constants or setup to test it

**Comment by Patta** [comment]
Nice! I will test it and give feedback.

**Comment by Patta** [comment]
@rupertgermann works great. A view things are missing like variables or the fluid rendering of category images without the need of an generic marker. A release would be cool. Thanks!
