### ISSUE TITLE
Cannot insert iframe in CKE editor for tt_news record (Typo3 v10)

### ISSUE THREAD

**Issue by baden32** [rupertgermann/tt_news#175]
Since I upgraded from Typo3 8 to 10.4, I cannot insert anymore the <iframe> tag in CKE editor for tt_news records.

I've added the specific config in my Presets.yaml and also in RTE.ts so everything is fine for normal "text" content element. I can insert & save content with <iframe src=....></iframe>. CKE Editor "iframe" has been added to editor settings, so I can insert an iframe just using the editor interface:

![image](https://user-images.githubusercontent.com/3597655/128354477-769262f3-5d2d-4c52-b11a-c4d428e85e12.png)

Unfortunately it does not work in tt_news description field because the editor options/config are obviously not the same:

![image](https://user-images.githubusercontent.com/3597655/128354643-763e07f8-91b2-488a-adae-4ad889acfb8c.png)

The editor config shown for normal text CE is defined in page.TS and my SitePresets.yaml listed below. 

So my question: what should I do in order to get the same editor config/option for tt_news description field?
Thanks in advance for your help.
Joel

My config is
Typo3 10.4.18
tt_news 10.0.0

rte.ts
# remove class="bodytext" from paragraphs
lib.parseFunc_RTE {
  allowTags := addToList(object,param,embed,iframe)  
}

`
editor:
 config:
  
    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css", "EXT:site_builder/Resources/Public/Css/rte.css"]

    stylesSet:
      - { name: "Bleu", element: "span", attributes: { class: "bleu"} }
      - { name: "Bouton", element: "a", attributes: { class: "btn btn-primary"} }
      - { name: "Test H", element: ["h1", "h2"], attributes: { class: "btn btn-primary"} }
#      - { name: "CTA", element: "a", attributes: { class: "cta-fond-blanc"} }
      - { name: "Table formation", element: "table", attributes: { class: "tbl-formation"} }
#      - { name: "Checkliste", element: "ul", attributes: { class: "check-list"} }

    format_tags: "p;h1;h2;h3;h4;h5;pre"

    toolbarGroups:
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing,   groups: [find, selection, spellchecker] }
      - { name: links }
      - { name: insert }
      - { name: tools }
      - { name: iframe }
      - { name: table }
      - { name: tabletools }
      - { name: document,  groups: [ mode, document, doctools ] }
      - { name: others }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph,   groups: [ list, indent, blocks, align, bidi ] }
      - { name: specialcharacters,   groups: [ insertcharacters ] }
      - "/"
      - { name: styles }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - nbsp
#      - font
      - find
      - iframe
#      - bidi
      - selectall

    allowTags:
      - iframe

    extraAllowedContent:
      - span
      - iframe

    removePlugins:
      - image

    removeButtons:
#      - Strike
      - Anchor
#      - Outdent
#      - Indent
#      - Blockquote
#      - JustifyBlock

# Allow s and u tag
processing:
  allowTags:
    - s
    - u
    - iframe

  allowTagsOutside:
    - iframe	

`

**Comment by baden32** [comment]
As found here https://docs.typo3.org/c/typo3/cms-rte-ckeditor/10.4/en-us/Configuration/ConfigureTypo3.html

I just added the following in my page.ts

RTE.config.tx_news_domain_model_news.bodytext.preset = minimal (or site_presets which is my site CKE config) but it has no effect at all (this is always the standard CKE version).

Looks like the own CKE config is not used. Why?

**Comment by baden32** [comment]
Problem solved!
In fact the default RTE preset is not used in tt_news edit interface. We effectively have to add/set that we want bodytext field should use your own preset.

Unfortunately, the doc found herehttps://docs.typo3.org/c/typo3/cms-rte-ckeditor/10.4/en-us/Configuration/ConfigureTypo3.html is wrong or not updated for Typo3 10 and tt_news 10.x:

RTE.config.tx_news_domain_model_news.bodytext.preset = site_presets
does not work

Should be
RTE.config.tt_news.bodytext.preset = site_presets
does work.

Hope this helps.
Joe

**Comment by Patta** [comment]
tx_news is not tt_news ;)

**Comment by baden32** [comment]
@Patta: you're right thanks a lot, I did not check this point.
