### ISSUE TITLE
$this->config['pageBreakToken'] might be NULL

### ISSUE THREAD

**Issue by xerc** [rupertgermann/tt_news#176]
NEWS_RELATED @ `[userFunc] => RG\TtNews\Plugin\TtNews->main_news`
https://github.com/rupertgermann/tt_news/blob/c70b1c6399cf2fa04e5147df25c6443cb66fe6ba/Classes/Plugin/TtNews.php#L1964

**Comment by rupertgermann** [comment]
fixed
