### ISSUE TITLE
Date/Time not set automatically

### ISSUE THREAD

**Issue by ghost** [rupertgermann/tt_news#18]
When I make a new news, the Date/Time is pre-filled with a datetime from the past. This happen on two different installations...

The pre-filled date/time seems to be the time when I installed tt_news.

**Comment by ShortSnow** [comment]
Fixed with https://github.com/rupertgermann/tt_news/pull/12

**Comment by derhecht** [comment]
And already merged so you can use current master to get fix automatically.

**Comment by ghost** [comment]
I downloaded master branch from Github, then uploaded to server and overwrote all files in typo3conf/ext/tt_news. Still, a new record is prefilled with an earlier date.

The pre-filled date seems to be the date when I first tried to create a new news.

**Comment by ShortSnow** [comment]
Please try: remove tt_news (not delete, no DB Compare ) -> clear all cache -> install tt_news
