### ISSUE TITLE
Compatibility with TYPO3 11.5 LTS

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#185]
A compatibility release for TYPO3 11.5 LTS would be great. Thanks

**Comment by rupertgermann** [comment]
hi Patrick,
did you have time to look in the branch https://github.com/rupertgermann/tt_news/tree/feature/typo3-v11 already?

**Comment by Patta** [comment]
Hi Rupert, thanks for your feedback. i have not had the opportunity to look at or test the branch yet. but i will. thanks a lot

**Comment by jigneshnitsan** [comment]
Hello @Patta 
Greetings of the day!

Firstly thank you for the great extension. Btw, May I know when you guys are planning to release the compatibility version of this extension? One of our customers is planning to upgrade the site with TYPO3 v11 but this is the only extension that is holding us back to do so.

Any reply would be appreciatable. 

Thanks!
Jignesh

**Comment by Patta** [comment]
@jigneshnitsan I am not the maintainer of tt_news, just a user and contributor. I am using tt_news in a big project, but currently have to wait for other extensions to finally test and upgrade tt_news for typo3 v11. You should require the [v11](https://github.com/rupertgermann/tt_news/tree/feature/typo3-v11) branch with composer and see if it works and then in the best case give feedback here. Additionally, when it comes to your customer projects, a donation to rupert could probably help to release a new version of tt_news for typo3 v11.

**Comment by swissdude** [comment]
Hi!
I'd be definitely willing to contribute financially to the development of a stable version for T3-v11 (maybe even v12?).
Or maybe even contribute with some coding (dunno if my coding skills are enough, though).
I'm in need for a stable version for an upcoming project for a customer. We do have a budget there and could probably use some of it for the development of the v11-version.
Anybody else willing to contribute some $$$?
@rupertgermann what would it take for you to finish v11?

**Comment by gedoens** [comment]
Just reporting in that the v11 branch is working without any noticeable issues for us after upgrading to typo3 v11. Thanks!

**Comment by Patta** [comment]
TypeError TYPO3\CMS\Core\Page\AssetCollector::addMedia() must be of the type string, null given #199

**Comment by Patta** [comment]
Backend news record category selection icon "indeterminate" is missing #200

**Comment by Patta** [comment]
@rupertgermann it would be great if you could publish a new tag/release of the v11 branch. Many thanks!
