### ISSUE TITLE
PHP Warning: Undefined array key "recursive." PHP 8.1

### ISSUE THREAD

**Issue by wmarie-joseph** [rupertgermann/tt_news#196]
Hello,

TYPO3 core version : 11.5.18
PHP version : 8.1
tt_news version : 11.0.0

I have this error when trying to visualize a page that has the tt_news (configured of course) plugin on it : 

![Capture d’écran 2022-11-09 à 15 13 01](https://user-images.githubusercontent.com/110893514/200854214-94f66317-1dad-4775-b55c-579ca8272e12.png)

Best regards,

Wilfrid

@rupertgermann

**Comment by jpmschuler** [comment]
~fixed in 2955cf9789a7ba6d0b5ee75e05931234bebdfec4 available in https://github.com/rupertgermann/tt_news/tree/feature/typo3-v11~

**Comment by jpmschuler** [comment]
sry looked up wrong version, still open
