### ISSUE TITLE
Compatibility release for TYPO3 12.4 LTS

### ISSUE THREAD

**Issue by sleepstorm** [rupertgermann/tt_news#202]
Hi there!
I am quite a fan of tt_news since I don't know how long and I'm wondering if there will be a tt_news version for TYPO3 v12.4?
We still maintain twelve TYPO3 v11.5 websites with tt_news with hundreds of news items in total.
Sadly the news_ttnewsimport extension is not an option anymore, so we are patiently waiting for a tt_news 12 version... 
Thanks!

**Comment by Patta** [comment]
I have a v12 branch in my fork of tt_news based on the [v11 PR](https://github.com/rupertgermann/tt_news/pull/201). I am currently testing and trying to get tt_news working with TYPO3 12 until the EOL of TYPO3 11. You are welcome to test and maybe contribute via direct PR in my fork. Greetz. https://github.com/Patta/tt_news/tree/v12

**Comment by rupertgermann** [comment]
a ton of thanks to Patta for the v12 branch :-)
I merged it to the new branch feature/typo3-v12 and will merge it to master after some testing
