### ISSUE TITLE
Major UI/UX issues in category select tree of tt_news v7.6.x

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#23]
If a sub-category is selected and the parent-category tree is closed, its not recognizable whether a sub-category was selected. In older tt_new versions like v3.6.x, parent-categories were marked with a color and contained a corresponding title when subcategories were selected. This makes it quite difficult to recognize whether sub-categories were chosen when a lot of nested categories are used.

Furthermore, it is not possible to determine how the sorting of the selected categories has been set. This could be explicitly set in older version like v3.6.x. In some configurations this is maybe helpful, especially if maxCatImages has set to 1 and only the first category image is rendered in frontend.

**Comment by derhecht** [comment]
Are you talking about BE or FE view? can you please add a screenshot which describes your problem? i think it is a may useful feature request but I could not approve it just based on your comment.

**Comment by Patta** [comment]
I mean in the Backend category select of a News item. Screenshot coming soon.

**Comment by Patta** [comment]
here my screens.
![tt_news_backend_cat-tree_no-visible-feedback1](https://cloud.githubusercontent.com/assets/2151127/20478236/7f6b4ca2-afd9-11e6-8950-874da1ddfecf.png)
![tt_news_backend_cat-tree_no-visible-feedback2](https://cloud.githubusercontent.com/assets/2151127/20478247/8363c820-afd9-11e6-8538-588b08703aea.png)

**Comment by derhecht** [comment]
As tt_news use the TYPO3 core tree view here and it is not featured by this we're not able to have visible feedback here too. May create a issue/feature request here: https://forge.typo3.org/projects/typo3cms-core

Otherwise you could create a PR by expanding ExtJS e.g. TYPO3.Components.Tree.StandardTree seen in tree.js in T3 core which will be placed in tt_news folder as first.

**Comment by Patta** [comment]
FYI: this is fixed in TYPO3 v8.x and the tree is rewritten.

![tree](https://cloud.githubusercontent.com/assets/2151127/20754753/b40d0e20-b70c-11e6-8e3d-2deda85cb8f1.png)
