### ISSUE TITLE
permissions: allowed/visible categories not working

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#31]
The permission options in be groups or be users "tt_news: allowed/visible categories" not working in TYPO3 7.6 and current tt_news. All categories are displayed no matter which is selected

User Tsconfig like 
`options.useListOfAllowedItems = 1`
`tt_newsPerms.tt_news_cat.allowedItems = 35,36,37`
or
`tt_newsPerms.tt_news_cat.excludeList = 1,2,3`
does not work too.

**Comment by derhecht** [comment]
Note (from changelog):
2006-08-18	Rupert Germann <rupi@gmx.li>
[...]
- new feature: added the category tree to be_users and be_groups records. Now it is possible to select the allowed and visible categories for a certain be_user/group with the category tree. If categories are selected in the be_user/group records the TSconfig settings 'options.useListOfAllowedItems', 'tt_newsPerms.tt_news_cat.includeList' and 'tt_newsPerms.tt_news_cat.allowedItems' have no effect anymore. (thanks to netcreators.nl for sponsoring this feature)

**Comment by derhecht** [comment]
Note (from changelog):
2008-04-14	Rupert Germann <rupi@gmx.li>
[...]
- improved the handling of allowed/disallowed categories in BE trees. FIXME -> making categories un-selectable with "tt_newsPerms.tt_news_cat.allowedItems" doesn't work currenlty

**Comment by derhecht** [comment]
After all:
- options.useListOfAllowedItems seems useless / will be removed during this fix
- use allowedItems OR excludeList but not both as it doesn't make sense at all

**Comment by derhecht** [comment]
Additionally:
- the hooks used by the configuration which defined in tx_ttnews_tcemain and tx_ttnews_tcemain_cmdmap only check on save not before create/update so in the end it might work but may not as expected?

**Comment by Patta** [comment]
Thank for your answers. I use only the select tree or allowedItems or excludeList. However, none of the three possibilities works or is taken over for the user of the usergroup. 

What do you mean with

> tx_ttnews_tcemain_cmdmap only check on save not before create/update

save the usergroup or the user?

**Comment by derhecht** [comment]
If you save the news only then the check of allowedItems etc. is made. So the editor sees all categories but can only save if only allowed are/were(!) selected.

May checkout my PR and test if it works correctly as I have tested.

**Comment by Patta** [comment]
The PR works, flash messages are shown. But, i expected from an option called "allowed/visible categories" that only selected (tree or tsconfig) categories are shown. It is important in a multisite environment. You do not want to represent a customer categories of another customer. I think that had already worked.

**Comment by derhecht** [comment]
But that is what the PR does. If allowedCat. are setup they will be used otherwise the tree.

**Comment by Patta** [comment]
The unauthorized or non-selected categories are still displayed to the user.

**Comment by derhecht** [comment]
Where? In FE or BE? As I wrote in BE it is normal/as coded. In FE it doesn't make sense.

**Comment by Patta** [comment]
In BE. It is not a good idea to make non-selected categories visible to the be users. Even if they can not be used. Maybe it is no longer part of the extension, but earlier the non-selected categories were hidden. If so, then this issue is probably a feature request.

**Comment by Patta** [comment]
With your feature 31 it works.

**Comment by derhecht** [comment]
Merged
