### ISSUE TITLE
Category tree not expanded by default

### ISSUE THREAD

**Issue by ToddHossack** [rupertgermann/tt_news#34]
Hi, 
In Typo3 7 LTS, when creating a record, the category tree is not expanded by default, even though it should as configured in the TCA file. Moving the "expandAll"  key/value under "appearance" works however. This is the correct spot according to the current TCA reference docs.
Cheers

**Comment by Patta** [comment]
If you have a lot of categories and subcategories, you do not want that all branches are expanded by default.

**Comment by derhecht** [comment]
I think same here as @Patta 

So issue is what? Anything left? May I would remove non-working stuff regarding this old behaviour to not confuse someone else.

**Comment by derhecht** [comment]
see https://github.com/rupertgermann/tt_news/pull/35
