### ISSUE TITLE
Workspaces: Publishing a news item deletes pictures

### ISSUE THREAD

**Issue by martinlipp** [rupertgermann/tt_news#37]
When publishing a news item to the Live workspace all images of the news item are getting deleted. In list view the news item is then showing an "File is missing! File /uploads/pics/xyz.jpg/ does not exist." error. Before publishing the file /uploads/pics/xyz.jpg does exist, after publishing the file is no longer there.
This does not happen when the news item was just send to another stage like "Ready to publish", the pictures only gets deleted on "Publish to LIVE".
See also [1].

Used versions:
tt_news: 3.6.3
TYPO3: 6.2.30

[1] https://forge.typo3.org/issues/62882

**Comment by derhecht** [comment]
sry, @martinlipp but 3.6.3 will not be supported any more. as 6.2 has a End of maintenance	2017-03 (https://typo3.org/download/) it will not be handled at all, afaik.

**Comment by ghost** [comment]
Sadly I can confirm this behaviour for the latest versions.

typo3: 7.6.16
tt_news: 7.6.3

**Comment by derhecht** [comment]
could not reproduced with current master on 8.7
