### ISSUE TITLE
RealURL: Sometimes wrong conversion of path to tx_ttnews[tt_news]

### ISSUE THREAD

**Issue by wloeer** [rupertgermann/tt_news#38]
Sometimes a (correct) path like:
.../article/date/2016/01/01/some-newstitle
Gets interpreted as:
?id=100&tx_ttnews[year]=2016&tx_ttnews[month]=01&tx_ttnews[day]=01&tx_ttnews[tt_news]=some-newstitle
instead of:
?id=100&tx_ttnews[year]=2016&tx_ttnews[month]=01&tx_ttnews[day]=01&tx_ttnews[tt_news]=23

Which results in "no news_id given" / "Keine news_id übergeben".

This seems to happen always, when I open such an URL directly and no RealURL-Cache exists. If Links are rendered in News-List/Latest, the conversion will usually be correct. But under some circumstances the error might happen here as well (I could find no rules to this).

This happens with:
Typo3 7.6
RealURL 1.13.7 and 2.1.5
tt_news 7.6.1 and 7.6.3

realurl_conf:
...
            'date' => array(
                
				array('GETvar' => 'tx_ttnews[year]' , ),
                array('GETvar' => 'tx_ttnews[month]' , ),
                array('GETvar' => 'tx_ttnews[day]' , ),
				
                array(
                    'GETvar' => 'tx_ttnews[tt_news]',
                    'lookUpTable' => array(
                        'table' => 'tt_news',
                        'id_field' => 'uid',
                        'alias_field' => 'title',
                        'addWhereClause'  => ' AND NOT deleted',
                        'useUniqueCache' => 1,
                        'useUniqueCache_conf' => array(
                            'strtolower' => 1,
                            'spaceCharacter' => '-',
                        ),
                    ),
                ),
            ),
...

This didn't happen before the recent Upgrade from 6.2 and older Versions of tt_news and RealURL (not sure which exactly), but same realurl_conf.  There also doesn't seem to be a problem with other extensions, like 'cal' for example.

Thanks!

**Comment by wloeer** [comment]
**Edit: this is incorrect - RealURL 2.1.5 seems equally affected (see my next comment)**

Have to correct myself:
The problem does apparently NOT happen with RealURL 2.1.5
(Here that version is not really an option sadly - I downgraded because of the removed support for nested URLs).

**Comment by derhecht** [comment]
As it is not a plan to support old versions of other extensions, I'll close this.

**Comment by wloeer** [comment]
Sorry for the back-and-forth, but I just rechecked with an earlier version of the site and discovered, that **the problem does exist also with RealURL 2.1.5**. (Problem was first reported after downgrade of RealURL, so I thought the newer version wasn't affected. No idea why it wasn't discovered earlier).

It's easy to test: Open a news-article, then truncate RealURL-Cache and reload the article (without generating the News-List first). The article should be found normally but isn't (at least on our site).

So I would like to reopen this issue. [Don't see a means to do this myself - sorry I am rather new to this.]
