### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#39]
Please add composer support. thanks

**Comment by derhecht** [comment]
What exactly do you mean by this? You can grab it by `"typo3-ter/tt-news": "^7.6",` in composer.json of your project.

**Comment by Patta** [comment]
Yes i know. Sorry for bad description. After latest merge from tt_news master with feature 31 i get a exception error on pages with the tt_news plugins. `Class 'tx_ttnews_div' not found. Error thrown in file
xxxxx\web\typo3conf\ext\tt_news\pi\class.tx_ttnews.php in line 3662.
`

**Comment by derhecht** [comment]
Please have a look again, sry.

**Comment by Patta** [comment]
thanks! Is there a scheduled release?

**Comment by derhecht** [comment]
Releases are @rupertgermann job. Sry. He's quite busy but may just ask him to do a new minor release, via mail.
