### ISSUE TITLE
Categories disappear in "News Admin" on collapse / show

### ISSUE THREAD

**Issue by konzertimpo** [rupertgermann/tt_news#46]
If I try to collapse or uncollapse an element in the Cateory List of the "News Admin", the clicked element and all of its childs disappear in **Typo3 7.6.15** and **tt_news 7.6.3**

**Additional Information:**
An ajax post request is fired to /typo3/ajax.php with the parameters
```
PM --> 0_1_38_ttnewscat
ajaxID --> txttnewsM1::expandCollapse
(id --> 76)
```
The response is empty...

**Comment by derhecht** [comment]
Reproduced.

**Comment by LeoniePhiline** [comment]
https://github.com/rupertgermann/tt_news/pull/51 fixes this for me.
