### ISSUE TITLE
TYPO3\CMS\Backend\Sprite\SpriteManager' not found

### ISSUE THREAD

**Issue by nabilou01** [rupertgermann/tt_news#47]
Dears

I've instaled TYPO3 8.6.0 and when i Try to install tt-news version 7.6.3 I have message error

	
Oops, an error occurred!
Class 'TYPO3\CMS\Backend\Sprite\SpriteManager' not found

Config:
Debian (8)
Ghostscript (9.05)
Apache (2.4.25)
ImageMagick (6.7.5)
MySQL (5.7.17)
OpenSSL (1.0.2k)
PHP (7.0.15)
phpMyAdmin (4.6.6)
SQLite (3.7.15.1)
TYPO3 (8.6.0)
Any Help, Please

Nabil

**Comment by nabilou01** [comment]
Dears 

Any Help? :)
This issue it's related 8.x version of Typo3?
The SpriteManager classes are not availabale in the 8.x version of Typo3 are ther any update to made?

regards

**Comment by derhecht** [comment]
We're still in TYPO3 7, moving to 8 when LTS will be available in release status.

**Comment by derhecht** [comment]
Please check, when approved it will be available in master.

**Comment by nabilou01** [comment]
Thank you
