### ISSUE TITLE
Class 'tx_ttnews_record_init_new' not found

### ISSUE THREAD

**Issue by Tonyt8** [rupertgermann/tt_news#49]
Hello,

Typo3 7.6.16 
php7-70 stable 
MySQL 5.6.19
I have been trying for 2 days to update tt_news from 7.6.1 to 7.6.3.
I find after I have updated to 7.6.2 or 7.6.3 I get the below error message when in template mode after I click the button "Edit the whole template record" when on a Template tools page.
+++++++++++++++++++++++++++++
Class 'tx_ttnews_record_init_new' not found

Error thrown in file
/kunden/112563_73765/rp-hosting/5005132/6005132/typo3cms/typo3_src-7.6.16/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 4535.

+++++++++++++++++++++++++++++
I get the same error message if I try to make a new news record or edit a news record.

I have been looking/googling looking for a solution, but cannot find the answer. 
Please can you help? If you need any more information please let me know.

Many thanks.

Regards,
Tony

**Comment by derhecht** [comment]
was introduced here: https://github.com/rupertgermann/tt_news/pull/12

**Comment by derhecht** [comment]
do you have a call stack? may a PHP 7 problem.

**Comment by Tonyt8** [comment]
Hi,
No, I do not have a call stack.

Regards,
Tony

**Comment by derhecht** [comment]
as class is available in autoloader and it works with PHP 5.6 and T3 7.6, could you may provide a call stack (e.g. by insert debug output GeneralUtility.php in line 4535) and some more details of your T3 instance (modules, composer mode?, operating system, ...)?

**Comment by LeoniePhiline** [comment]
@Tonyt8
Also try if removing (recusively deleting) the typo3temp/autoload/ folder helps. That should have been done automatically, but who knows why it might have failed for you.

**Comment by rupertgermann** [comment]
seems to be outdated. closed.
