### ISSUE TITLE
Typo3 7.6 with tt_news version 7.6.1  Backend module gives error ( No back-end function registered for ajaxID "txttnewsM1::loadList". )

### ISSUE THREAD

**Issue by Vish05** [rupertgermann/tt_news#5]
I am using Typo3 7.6 with latest version of tt_news ( 7.6.1 ). For the back-end module i got the below error. "No backend function registered for ajaxID "txttnewsM1::loadList". Please help me to resolve that error.

**Comment by rreichen** [comment]
With the same Versions of TYPO3 and tt_news I recognized the same message.

**Comment by taaank** [comment]
With the same Versions of TYPO3 and tt_news I recognized the same message.

**Comment by eLJoD** [comment]
Same problem here.
Change in ext_localconf.php Line 35 and 36 in:
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler (
    'txttnewsM1::expandCollapse',
    TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('tt_news').'mod1/index.php:tx_ttnews_module1->ajaxExpandCollapse',
    false
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler (
    'txttnewsM1::loadList',
    TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('tt_news').'mod1/index.php:tx_ttnews_module1->ajaxLoadList',
    false
);

**Comment by taaank** [comment]
Thanks! It works perfect!!!)
