### ISSUE TITLE
cannot set moduleTemplate

### ISSUE THREAD

**Issue by hannesbochmann** [rupertgermann/tt_news#55]
Is it possible to remove the logging in the backend module (tx_ttnews_module1::main()) when the template can't be found or at least lower the severity? 
This message floods our devlog and seems to be uncritical as the template is fetched with a fallback anyways. Or is there something else I can do to make those messages disappear? Seems like the problem is the symlink from typo3_src/typo3 to typo3 in the webroot but this can't/shouldn't be changed.

**Comment by derhecht** [comment]
Please approve PR https://github.com/rupertgermann/tt_news/pull/57 if it fits your need.

**Comment by hannesbochmann** [comment]
This fixes the problem but I still wonder why it's necessary to log when the module template can't be found as a fallback is implemented anyways. This way you get a warning about something that works.

**Comment by derhecht** [comment]
in the end the log helped us here to fix this code after core code has changed in way to reference admin templates. when it changed next time, logging will help us again. so far: thanks for the input!
