### ISSUE TITLE
Typo3 7.6.2 with tt_news version 7.6.1 produces following errors in back-end:

### ISSUE THREAD

**Issue by janiCGN** [rupertgermann/tt_news#7]
Typo3 7.6.2 with tt_news version 7.6.1 produces following errors in back-end:
1. Icons are missing in list view.
   ![bildschirmfoto 2016-01-27 um 11 57 09](https://cloud.githubusercontent.com/assets/16917294/12612232/7634f954-c4f1-11e5-9e0a-15a10caaf3b8.png)
2. Following error message appears, while selecting a category:
   "The requested URL /typo3/ajax.php was not found on this server.“
   ![bildschirmfoto 2016-01-27 um 11 57 25](https://cloud.githubusercontent.com/assets/16917294/12612236/7e40addc-c4f1-11e5-9909-edeb5cbf9ba9.png)

**Comment by rupertgermann** [comment]
hi,

the newsadmin module is not yet 7.6 ready (thats the reason why it is disabled by default)
I plan to work on it but I'm currently quite busy with other stuff.

greetings rupi

**Comment by fabrikatur** [comment]
Hi.
Any further plans on getting the module going again in full?
Thanks & cheers!

**Comment by w010** [comment]
Hi Rupert! Do you plan to still work on adjusting tt_news to TYPO 7.6?
I have done some fixes for icons in news admin module. The essential functionality is working for me with T3 7.6.11 and PHP 5.5.38.
Do you wish to see that changes? I will put it on github later this week.

**Comment by w010** [comment]
Please take a look, or maybe it will be helpful for someone
https://github.com/w010/tt_news

**Comment by derhecht** [comment]
what about rebasing (if necessary) and creating a pull request for merge? may create a fork (instead of a new (standalone) repository) and mention this issue in the commit message to have everything linked together.

**Comment by w010** [comment]
Rupert didn't answer, and I hadn't time to think about it. I'm not sure this repo is still active. So I made the fixes and pushed to github to make them available. We'll see later. It'd be nice to merge this in the future.
