### ISSUE TITLE
Column `l10n_state` missing from table `tt_news`

### ISSUE THREAD

**Issue by sir-gawain** [rupertgermann/tt_news#70]
The table tt_news is missing the column `l10n_state` which leads to a SQL error during the SQL query.

**Comment by derhecht** [comment]
During "the" SQL query? Which one is meant here? Is this a new column need by TYPO3 8?

**Comment by sir-gawain** [comment]
Yes, its a new column used in 8. Not sure what its used for, but it got appended to the normal tt_news query by the system.
Perhaps this helps: https://docs.typo3.org/typo3cms/extensions/core/8-dev/Changelog/8.6/Feature-51291-SynchronizedFieldValuesInLocalizedRecords.html
