### ISSUE TITLE
Datetime fields are limited to 20 characters

### ISSUE THREAD

**Issue by sir-gawain** [rupertgermann/tt_news#72]
Datetime fields are limited to a maximum of 20 characters in TCA. TYPO3 8 sometimes generates longer strings in a format like this: 2016-11-17T12:57:00+00:00 which leads the to error mesage that the time string cannot be parsed (because the limit to 20 cuts it to 2016-11-17T12:57:00+).

**Comment by derhecht** [comment]
see https://github.com/rupertgermann/tt_news/pull/73
