### ISSUE TITLE
Shariff extension  - social media

### ISSUE THREAD

**Issue by nabilou01** [rupertgermann/tt_news#78]
Dear
I'm using tx_news 6.0.0 and rx_shariff 10.0.0 and i have a little issue when i have XING button in place of G+.
It's normal?
Regards

Nabil

**Comment by derhecht** [comment]
1. We are at tt_news 8.x (7.x since months), 6.x is far old.
2. Sounds like a rx_shariff problem at all.
3. Which TYPO3 version?
4. URL? Link?

**Comment by Patta** [comment]
@nabilou01 wrong repo > https://github.com/georgringer/news

**Comment by rupertgermann** [comment]
no tt_news problem
