### ISSUE TITLE
typo3 8 LTS fatal in pi/class.tx_ttnews.php

### ISSUE THREAD

**Issue by alexanderhaensch** [rupertgermann/tt_news#80]
i get Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getStorageSiterootPids() | Error thrown in file /var/www/typo3/htdocs/typo3conf/ext/tt_news/pi/class.tx_ttnews.php in line 3536.
on typ3 8.6 with current master.
Looks like 
getStorageSiterootPids() is deprecated 
https://github.com/rupertgermann/tt_news/blob/a9322308bef644b614fa9831c1c743d8d1f0466a/pi/class.tx_ttnews.php#L3536

**Comment by LeoniePhiline** [comment]
Duplicate of #87.

**Comment by ingeniumdesign** [comment]
same here:

> Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getStorageSiterootPids() 
> 
> Error thrown in file
> /home/bbdev02/public_html/users/basti/fsfm/typo3conf/ext/tt_news/pi/class.tx_ttnews.php in line 3536.

**Comment by rupertgermann** [comment]
please use latest master
