### ISSUE TITLE
Category list is empty

### ISSUE THREAD

**Issue by anshlv** [rupertgermann/tt_news#81]
When using a "Create new content" function, adding a tt_news plugin, the category tree is empty. Selection of a category is only possible via editing a flexform in the database directly and works till the next time a content record gets edited.

**Comment by MarcoSie** [comment]
We facing a similar Issue, but it includes "Creating", "Saving" and "Opening". I cant tell if this is related or not.

I feel this occurs with the loading of the list.  I made like 30-50 Tests ("Saving", "Saving Close"  and "Open", i could reproduce it only two times. Some colleague have it like almost everytime, some other never.

My guess is that this could be related to Internet-Connections or high System workloads, it is hard to test and to reproduce. Like Ajax-Timeout leads to no JSON-Output.


* With Typo3 8.7.7

**Comment by rupertgermann** [comment]
cannot reproduce. please re-open if the problem still exists.
