### ISSUE TITLE
There is no includeLibs in TYPO3 7.6 anymore

### ISSUE THREAD

**Issue by LuckyFellow** [rupertgermann/tt_news#86]
I am migrating an old TYPO3 to TYPO3 7.6.
The TYPO3 installation uses a custom **itemMarkerArrayFunc.php** script, which was included via TypoScript: **includeLibs.displayFileLinks**

As of TYPO3 7.4, the TypoScript funktion **includeLibs** has been removed without substitution:
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Breaking

I can't find an example in tt_news/res/ of how the itemMarkerArrayFunc.php script should be included in TYPO3 7.4 and newer.

Is there a way to include it in TYPO3 7.6, if yes, how?
If not, what would be the way to go / which hooks should be used, to implement my own logic?

**Comment by w010** [comment]
You can include such files manually in ext_localconf or AdditionalConfiguration.

**Comment by LuckyFellow** [comment]
Thank you very much.

For me it works to include the file in ext_localconf.php like this:

```
$extensionPath = rtrim(\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('MY_EXTENSION'), "/");
require_once($extensionPath."/lib/ttnews_itemMarkerArrayFunc.php");

```

**Comment by w010** [comment]
But it's not the best method. What you probably need, is to use extraItemMarkerHook. Just register it in your ext_localconf and it will be included automatically:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['tt_news']['extraItemMarkerHook'][] = 'EXT:my_ext/Classes/Hooks/TtNews/GeneralHooks.php:GeneralHooks';`

or better, using namespaces which trigger autoload if proper naming/directory structure:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['tt_news']['extraItemMarkerHook'][] = 'MyNamespace\MyExt\Hooks\TtNews\GeneralHooks';`

For namespaces in TYPO3 please refer to: [https://docs.typo3.org/typo3cms/CoreApiReference/7.6/ApiOverview/Namespaces/](https://docs.typo3.org/typo3cms/CoreApiReference/7.6/ApiOverview/Namespaces/)
