### ISSUE TITLE
getStorageSiterootPids() removed in 8LTS

### ISSUE THREAD

**Issue by sir-gawain** [rupertgermann/tt_news#87]
Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getStorageSiterootPids()

Error thrown in file
/var/www/html/8.7/typo3conf/ext/tt_news/pi/class.tx_ttnews.php in line 3536.

**Comment by adrienjacob** [comment]
This is apparently related to this deprecation : https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Deprecation#Deprecation:_.2365790_-_Remove_pages.storage_pid_and_logic
I don't know how to replace this deprecated method, but anyway a temporary workaround is to set "useStoragePid" to 0 in typo3conf/LocalConfiguration.php (for some reason this option cannot be accessed in the extension manager).

**Comment by adrienjacob** [comment]
And there are suggested PR :  https://github.com/rupertgermann/tt_news/pull/64 & https://github.com/rupertgermann/tt_news/pull/65

**Comment by DavidBruchmann** [comment]
PR : #64 & #65 are probably based on the wrong branch, should be `feature/87refactoring`.  

> for some reason this option cannot be accessed in the extension manager

The option is removed, so to change the configuration of it, the value had to be changed before update.
Nevertheless the code had to be changed accordingly and then the value wouldn't matter anyway :/

**Comment by rupertgermann** [comment]
please use latest master where this issue should be fixed
