### ISSUE TITLE
Error in BE module in 8 LTS

### ISSUE THREAD

**Issue by dklimpel** [rupertgermann/tt_news#88]
I get in TYPO3 8 LTS in the BE module an error:

> Fatal error: Uncaught Error: Class 'TYPO3\CMS\Backend\Utility\IconUtility' not found in /home/www/testix2/typo3conf/ext/tt_news/lib/class.tx_ttnews_recordlist.php:197

I have created a patch.
[class.tx_ttnews_recordlist.patch.txt](https://github.com/rupertgermann/tt_news/files/1203273/class.tx_ttnews_recordlist.patch.txt)

Replace
>\TYPO3\CMS\Backend\Utility\IconUtility::skinImg

with
>\WMDB\TtNews\Utility\IconFactory::skinImg

**Comment by rupertgermann** [comment]
please use latest master where this issue should be fixed
