### ISSUE TITLE
define $tempColumns in TCA overrides

### ISSUE THREAD

**Issue by hannesbochmann** [rupertgermann/tt_news#92]
In the 87 refactoring branch the variables $tempColumns get enhanced but not defined (inside the TCE overrides). If another extensions uses the same variable name in TCA overrides (like be_secure_pw does) existing values will be kept leading to TCA/SQL errors because there are fields in the TCA that don't exist in the database.
In the master branch the variables were defined not just enhanced so there is no problem.

I experienced this problem during the Upgrade Wizard "Execute database migrations on single rows" when updating to TYPO3 8.7. The following error popped up:

Uncaught TYPO3 Exception: An exception occurred while executing 'UPDATE `be_groups` SET `tx_besecurepw_lastpwchange` = ? WHERE `uid` = ?' with params [null, 1]:\n\nUnknown column 'tx_besecurepw_lastpwchange' in 'field list' | Doctrine\\DBAL\\Exception\\InvalidFieldNameException thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 73

This is because be_secure_pw was the last extension loaded before tt_news which defined $tempColumns.

**Comment by adrienjacob** [comment]
Hi @hannesbochmann, I believe this has been solved in https://github.com/rupertgermann/tt_news/commit/0a8b0d360f588d27842966d4fd421524dd8c7bc6

**Comment by hannesbochmann** [comment]
No, not completely. If an extension after tt_news uses the same variable, the problem would occur there.
So the best would be to unset the variable afterwards or even better, put the complete code block into an anonymous function (@see https://github.com/DMKEBUSINESSGMBH/mkvarnish/blob/master/ext_localconf.php). This is better for performance reasons and solves the problem more elegant.

**Comment by hannesbochmann** [comment]
Update: In the current master the problem is fixed but not in the the 8.7 refactoring branch.

**Comment by rupertgermann** [comment]
fixed in current master which is compatible with TYPO3 8.7 up to 9.5
