### ISSUE TITLE
tt_news 8.7.6 

### ISSUE THREAD

**Issue by williwacker** [rupertgermann/tt_news#96]
Have installed your 8.7.6 version. When I want to edit the category of an existing news article the field is red and I get this exception: 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'RG\TtNews\tx_ttnews_div' not found | Error thrown in file /www/htdocs/............/typo3conf/ext/tt_news/Classes/Tree/TableConfiguration/NewsDatabaseTreeDataProvider.php in line 27. Requested URL: http://www........../typo3/index.php?ajaxID=%2Fajax%2Frecord%2Ftree%2FfetchData&ajaxToken=ecf89975b3c285cdfb7d1aec03de3452b12a92b4&tableName=tt_news&fieldName=category&uid=213&recordTypeValue=0&dataStructureIdentifier=&flexFormSheetName=&flexFormFieldName=&flexFormContainerName=&flexFormContainerIdentifier=&flexFormContainerFieldName=&flexFormSectionContainerIsNew=&command=edit`

Any idea why this class doesn't get loaded? Tx

**Comment by rupertgermann** [comment]
because the classname is actually wrong ;-)
fixed it:
https://github.com/rupertgermann/tt_news/commit/4b9da3d535ce1ed9e320ec2c56345ec75688d672

**Comment by williwacker** [comment]
Hi Rupert,
Have found the place. 
Class NewsDatabaseTreeDataProvider.php  needs to be changed at two places:  
tx_ttnews_div  to  Div
use RG\TtNews\Div;
and   $allowedItems) : Div::getAllowedTreeIDs();

**Comment by rupertgermann** [comment]
yes, my last commit should fix this. Does it work for you ?

**Comment by williwacker** [comment]
yes
