### ISSUE TITLE
PHP runtime deprecation notice in belog

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#99]
TYPO3 8.7.10 and PHP 7.2.2

> Core: Error handler (FE): PHP Runtime Deprecation Notice: The each() function is deprecated. This message will be suppressed on further calls in /.../web/typo3conf/ext/tt_news/pi/class.tx_ttnews.php line 1550

**Comment by adrienjacob** [comment]
Hi, I submitted a PR for this : https://github.com/rupertgermann/tt_news/pull/97

**Comment by Patta** [comment]
@adrienjacob ah nice. There is another each() in line 1888

> Core: Error handler (FE): PHP Runtime Deprecation Notice: The each() function is deprecated. This message will be suppressed on further calls in /.../web/typo3conf/ext/tt_news/pi/class.tx_ttnews.php line 1888

**Comment by adrienjacob** [comment]
You're right, I corrected this one as well !

**Comment by rupertgermann** [comment]
already fixed
